### ISSUE TITLE
Some users unable to rate courses (even when logged in)

### ISSUE THREAD

**Issue by ConorRoberts** [ConorRoberts/dogs-barking#135]

**Comment by ConorRoberts** [comment]
Not a bug. Actually a feature.

Forgot I added this check

```ts
const canRateCourse = user && user?.takenCourses.some((e) => e.id === courseId);
```

@PhilipK13 Adding a toast notification to tell people when they can't rate courses.

**Comment by PhilipK13** [comment]
Users are now informed when they can't rate a course and why.
